name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout files
      uses: actions/checkout@v2

    - name: Install Node 14
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Install eslint
      run: npm install -g eslint

    - name: Install dependencies
      run: npm i

    - name: Run eslint
      run: eslint .

    - name: Build
      run: npm run build
